{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sonja.fullname" $ }}-{{ .name }}
  labels:
    app: {{ template "sonja.fullname" $ }}-{{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sonja.fullname" $ }}-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ template "sonja.fullname" $ }}-{{ .name }}
    spec:
      containers:
      - name:  {{ .name }}
        image: uboot/sonja-{{ .name }}:{{ $.Values.channel }}
        livenessProbe:
          httpGet:
            path: {{ .pingUrl | default "/ping" }}
            port: 8080
          initialDelaySeconds: 300
        env:
        - name: MYSQL_URL
          value: {{ $.Release.Name }}-mysql
        - name: MYSQL_ROOT_PASSWORD
          value: {{ $.Values.mysql.auth.rootPassword }}
        - name: REDIS_HOST
          value: {{ $.Release.Name }}-redis-master
        - name: SONJA_CRAWLER_URL
          value: {{ template "sonja.fullname" $ }}-crawler
        - name: SONJA_SCHEDULER_URL
          value: {{ template "sonja.fullname" $ }}-scheduler
        - name: SONJA_LINUXAGENT_URL
          value: {{ template "sonja.fullname" $ }}-linux-agent
        - name: SONJA_WINDOWSAGENT_URL
          value: {{ template "sonja.fullname" $ }}-windows-agent
        - name: SONJA_INITIAL_USER
          value: {{ $.Values.auth.user }}
        - name: SONJA_INITIAL_PASSWORD
          value: {{ $.Values.auth.password }}
        - name: SONJA_INITIAL_ECOSYSTEM
          value: {{ $.Values.initialEcosystem }}
        - name: SONJA_SECRET_KEY
          value: {{ $.Values.auth.secretKey }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sonja.fullname" $ }}-linux-agent
  labels:
    app: {{ template "sonja.fullname" $ }}-linux-agent
spec:
  replicas: {{ $.Values.linux.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ template "sonja.fullname" $ }}-linux-agent
  template:
    metadata:
      labels:
        app: {{ template "sonja.fullname" $ }}-linux-agent
    spec:
      containers:
      - name:  linux-agent
        image: uboot/sonja-agent:{{ $.Values.channel }}
        livenessProbe:
          httpGet:
            path: {{ .pingUrl | default "/ping" }}
            port: 8080
          initialDelaySeconds: 300
        env:
        - name: MYSQL_URL
          value: {{ $.Release.Name }}-mysql
        - name: MYSQL_ROOT_PASSWORD
          value: {{ $.Values.mysql.auth.rootPassword }}
        - name: REDIS_HOST
          value: {{ $.Release.Name }}-redis-master
        - name: SONJA_SCHEDULER_URL
          value: {{ template "sonja.fullname" $ }}-scheduler
        - name: SONJA_AGENT_OS
          value: Linux
        - name: SONJA_MTU
          value: "{{ $.Values.mtu | default 1500 }}"
        - name: DOCKER_HOST
          value: 127.0.0.1:2375
      - name: docker
        image: docker:19.03.12-dind
        command: 
        - "dockerd"
        - "--mtu"
        - {{ $.Values.mtu | quote }}
{{- range $.Values.insecureRegistries }}
        - "--insecure-registry"
        - {{ . | quote }}
{{- end }}
        - "-H"
        - "tcp://"
        securityContext:
          privileged: true
---
{{- range untilStep 0 (int .Values.windows.replicas) 1 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sonja.fullname" $ }}-windows-agent-{{ . }}
  labels:
    app: {{ template "sonja.fullname" $ }}-windows-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sonja.fullname" $ }}-windows-agent
      deployment: {{ template "sonja.fullname" $ }}-windows-agent-{{ . }}
  template:
    metadata:
      labels:
        app: {{ template "sonja.fullname" $ }}-windows-agent
        deployment: {{ template "sonja.fullname" $ }}-windows-agent-{{ . }}
    spec:
      containers:
      - name:  windows-agent
        image: uboot/sonja-agent:{{ $.Values.channel }}
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 300
        env:
        - name: MYSQL_URL
          value: {{ $.Release.Name }}-mysql
        - name: MYSQL_ROOT_PASSWORD
          value: {{ $.Values.mysql.auth.rootPassword }}
        - name: REDIS_HOST
          value: {{ $.Release.Name }}-redis-master
        - name: SONJA_SCHEDULER_URL
          value: {{ template "sonja.fullname" $ }}-scheduler
        - name: SONJA_AGENT_OS
          value: Windows
        - name: SONJA_MTU
          value: "{{ $.Values.mtu | default 1500 }}"
        - name: DOCKER_HOST
          value: {{ template "sonja.fullname" $ }}-windows-docker-{{ . }}:2375
---
{{- end }}
