{{- range untilStep 0 (int .Values.windows.replicas) 1 }}
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: {{ template "sonja.fullname" $ }}-windows-docker-{{ . }}
  labels:
    app: {{ template "sonja.fullname" $ }}-windows-docker-{{ . }}
    kubevirt.io/os: win2k19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sonja.fullname" $ }}-windows-docker-{{ . }}
  template:
    metadata:
      generation: 1
      labels:
        kubevirt.io/os: windows
        app: {{ template "sonja.fullname" $ }}-windows-docker-{{ . }}
    spec:
      terminationGracePeriodSeconds: 30
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4096M
        machine:
          type: q35
        devices:
          disks:
          - name: windows-server
            disk:
              bus: virtio
          - name: cloudinitdisk
            cdrom:
              bus: sata
      volumes:
      - name: windows-server
        containerDisk:
          image: {{ $.Values.windows.image }}
      - name: cloudinitdisk
        cloudInitConfigDrive:
          userData: |
            #cloud-config
            write_files:
            - encoding: b64
              content: {{ template "sonja.daemonJsonB64" $ }}
              path: C:\ProgramData\Docker\config\daemon.json
              permissions: '0644'
            runcmd:
            - 'powershell "Restart-Service docker"'
---
{{- end }}
