FROM node:15.7.0 as builder

WORKDIR /app

RUN npm install -g ember-cli@3.23.0

RUN git clone https://github.com/uboot/sonja-frontend.git \
  && cd sonja-frontend \
  && git checkout 5aeae7feebb4037acab7e7b65a29fbf2b2b7108d \
  && npm install \
  && ember build --environment production


FROM nginx:1.19.6

COPY --from=builder /app/sonja-frontend/dist /usr/share/nginx/html
COPY frontend/ping.json /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/nginx.conf