FROM node:15.7.0 as builder

WORKDIR /app

RUN npm install -g ember-cli@3.23.0

RUN git clone https://github.com/uboot/conan-ci-frontend.git \
  && cd conan-ci-frontend \
  && git checkout 600575f5b2ce01d072959edbeb63218a3bb24af2 \
  && npm install \
  && ember build --environment production


FROM nginx:1.19.6

COPY --from=builder /app/conan-ci-frontend/dist /usr/share/nginx/html
COPY frontend/ping.json /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/nginx.conf