FROM alpine:3.12

RUN apk add --no-cache \
		docker \
		openssh-client \
		git \
		py3-pip \
		py3-wheel \
		py3-mysqlclient

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/

RUN pip3 install --no-cache-dir -r requirements.txt

COPY conanci /usr/src/app/conanci
COPY public /usr/src/app

EXPOSE 8080

ENTRYPOINT ["python3"]

CMD ["-m", "swagger_server"]