# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.build_relationships_package_data import BuildRelationshipsPackageData  # noqa: F401,E501
from swagger_server import util


class BuildRelationshipsPackage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: BuildRelationshipsPackageData=None):  # noqa: E501
        """BuildRelationshipsPackage - a model defined in Swagger

        :param data: The data of this BuildRelationshipsPackage.  # noqa: E501
        :type data: BuildRelationshipsPackageData
        """
        self.swagger_types = {
            'data': BuildRelationshipsPackageData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'BuildRelationshipsPackage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Build_relationships_package of this BuildRelationshipsPackage.  # noqa: E501
        :rtype: BuildRelationshipsPackage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> BuildRelationshipsPackageData:
        """Gets the data of this BuildRelationshipsPackage.


        :return: The data of this BuildRelationshipsPackage.
        :rtype: BuildRelationshipsPackageData
        """
        return self._data

    @data.setter
    def data(self, data: BuildRelationshipsPackageData):
        """Sets the data of this BuildRelationshipsPackage.


        :param data: The data of this BuildRelationshipsPackage.
        :type data: BuildRelationshipsPackageData
        """

        self._data = data
