# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.build_relationships_log_data import BuildRelationshipsLogData  # noqa: F401,E501
from swagger_server import util


class BuildRelationshipsLog(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: BuildRelationshipsLogData=None):  # noqa: E501
        """BuildRelationshipsLog - a model defined in Swagger

        :param data: The data of this BuildRelationshipsLog.  # noqa: E501
        :type data: BuildRelationshipsLogData
        """
        self.swagger_types = {
            'data': BuildRelationshipsLogData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'BuildRelationshipsLog':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Build_relationships_log of this BuildRelationshipsLog.  # noqa: E501
        :rtype: BuildRelationshipsLog
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> BuildRelationshipsLogData:
        """Gets the data of this BuildRelationshipsLog.


        :return: The data of this BuildRelationshipsLog.
        :rtype: BuildRelationshipsLogData
        """
        return self._data

    @data.setter
    def data(self, data: BuildRelationshipsLogData):
        """Sets the data of this BuildRelationshipsLog.


        :param data: The data of this BuildRelationshipsLog.
        :type data: BuildRelationshipsLogData
        """

        self._data = data
