# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.build_relationships_commit_data import BuildRelationshipsCommitData  # noqa: F401,E501
from swagger_server import util


class BuildRelationshipsCommit(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: BuildRelationshipsCommitData=None):  # noqa: E501
        """BuildRelationshipsCommit - a model defined in Swagger

        :param data: The data of this BuildRelationshipsCommit.  # noqa: E501
        :type data: BuildRelationshipsCommitData
        """
        self.swagger_types = {
            'data': BuildRelationshipsCommitData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'BuildRelationshipsCommit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Build_relationships_commit of this BuildRelationshipsCommit.  # noqa: E501
        :rtype: BuildRelationshipsCommit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> BuildRelationshipsCommitData:
        """Gets the data of this BuildRelationshipsCommit.


        :return: The data of this BuildRelationshipsCommit.
        :rtype: BuildRelationshipsCommitData
        """
        return self._data

    @data.setter
    def data(self, data: BuildRelationshipsCommitData):
        """Sets the data of this BuildRelationshipsCommit.


        :param data: The data of this BuildRelationshipsCommit.
        :type data: BuildRelationshipsCommitData
        """

        self._data = data
