# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.channel_attributes import ChannelAttributes  # noqa: F401,E501
from swagger_server.models.profile_relationships import ProfileRelationships  # noqa: F401,E501
from swagger_server import util


class Channel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, type: str=None, attributes: ChannelAttributes=None, relationships: ProfileRelationships=None):  # noqa: E501
        """Channel - a model defined in Swagger

        :param id: The id of this Channel.  # noqa: E501
        :type id: str
        :param type: The type of this Channel.  # noqa: E501
        :type type: str
        :param attributes: The attributes of this Channel.  # noqa: E501
        :type attributes: ChannelAttributes
        :param relationships: The relationships of this Channel.  # noqa: E501
        :type relationships: ProfileRelationships
        """
        self.swagger_types = {
            'id': str,
            'type': str,
            'attributes': ChannelAttributes,
            'relationships': ProfileRelationships
        }

        self.attribute_map = {
            'id': 'id',
            'type': 'type',
            'attributes': 'attributes',
            'relationships': 'relationships'
        }
        self._id = id
        self._type = type
        self._attributes = attributes
        self._relationships = relationships

    @classmethod
    def from_dict(cls, dikt) -> 'Channel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Channel of this Channel.  # noqa: E501
        :rtype: Channel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Channel.


        :return: The id of this Channel.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Channel.


        :param id: The id of this Channel.
        :type id: str
        """

        self._id = id

    @property
    def type(self) -> str:
        """Gets the type of this Channel.


        :return: The type of this Channel.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Channel.


        :param type: The type of this Channel.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def attributes(self) -> ChannelAttributes:
        """Gets the attributes of this Channel.


        :return: The attributes of this Channel.
        :rtype: ChannelAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: ChannelAttributes):
        """Sets the attributes of this Channel.


        :param attributes: The attributes of this Channel.
        :type attributes: ChannelAttributes
        """

        self._attributes = attributes

    @property
    def relationships(self) -> ProfileRelationships:
        """Gets the relationships of this Channel.


        :return: The relationships of this Channel.
        :rtype: ProfileRelationships
        """
        return self._relationships

    @relationships.setter
    def relationships(self, relationships: ProfileRelationships):
        """Sets the relationships of this Channel.


        :param relationships: The relationships of this Channel.
        :type relationships: ProfileRelationships
        """

        self._relationships = relationships
