# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ecosystem_relationships_builds_links import EcosystemRelationshipsBuildsLinks  # noqa: F401,E501
from swagger_server import util


class EcosystemRelationshipsBuilds(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: EcosystemRelationshipsBuildsLinks=None):  # noqa: E501
        """EcosystemRelationshipsBuilds - a model defined in Swagger

        :param links: The links of this EcosystemRelationshipsBuilds.  # noqa: E501
        :type links: EcosystemRelationshipsBuildsLinks
        """
        self.swagger_types = {
            'links': EcosystemRelationshipsBuildsLinks
        }

        self.attribute_map = {
            'links': 'links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'EcosystemRelationshipsBuilds':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ecosystem_relationships_builds of this EcosystemRelationshipsBuilds.  # noqa: E501
        :rtype: EcosystemRelationshipsBuilds
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> EcosystemRelationshipsBuildsLinks:
        """Gets the links of this EcosystemRelationshipsBuilds.


        :return: The links of this EcosystemRelationshipsBuilds.
        :rtype: EcosystemRelationshipsBuildsLinks
        """
        return self._links

    @links.setter
    def links(self, links: EcosystemRelationshipsBuildsLinks):
        """Sets the links of this EcosystemRelationshipsBuilds.


        :param links: The links of this EcosystemRelationshipsBuilds.
        :type links: EcosystemRelationshipsBuildsLinks
        """

        self._links = links
