# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ecosystem_relationships_recipes_links import EcosystemRelationshipsRecipesLinks  # noqa: F401,E501
from swagger_server import util


class EcosystemRelationshipsRecipes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: EcosystemRelationshipsRecipesLinks=None):  # noqa: E501
        """EcosystemRelationshipsRecipes - a model defined in Swagger

        :param links: The links of this EcosystemRelationshipsRecipes.  # noqa: E501
        :type links: EcosystemRelationshipsRecipesLinks
        """
        self.swagger_types = {
            'links': EcosystemRelationshipsRecipesLinks
        }

        self.attribute_map = {
            'links': 'links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'EcosystemRelationshipsRecipes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ecosystem_relationships_recipes of this EcosystemRelationshipsRecipes.  # noqa: E501
        :rtype: EcosystemRelationshipsRecipes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> EcosystemRelationshipsRecipesLinks:
        """Gets the links of this EcosystemRelationshipsRecipes.


        :return: The links of this EcosystemRelationshipsRecipes.
        :rtype: EcosystemRelationshipsRecipesLinks
        """
        return self._links

    @links.setter
    def links(self, links: EcosystemRelationshipsRecipesLinks):
        """Sets the links of this EcosystemRelationshipsRecipes.


        :param links: The links of this EcosystemRelationshipsRecipes.
        :type links: EcosystemRelationshipsRecipesLinks
        """

        self._links = links
