# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ecosystem_relationships_channels_data import EcosystemRelationshipsChannelsData  # noqa: F401,E501
from swagger_server import util


class EcosystemRelationshipsChannels(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[EcosystemRelationshipsChannelsData]=None):  # noqa: E501
        """EcosystemRelationshipsChannels - a model defined in Swagger

        :param data: The data of this EcosystemRelationshipsChannels.  # noqa: E501
        :type data: List[EcosystemRelationshipsChannelsData]
        """
        self.swagger_types = {
            'data': List[EcosystemRelationshipsChannelsData]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'EcosystemRelationshipsChannels':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ecosystem_relationships_channels of this EcosystemRelationshipsChannels.  # noqa: E501
        :rtype: EcosystemRelationshipsChannels
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[EcosystemRelationshipsChannelsData]:
        """Gets the data of this EcosystemRelationshipsChannels.


        :return: The data of this EcosystemRelationshipsChannels.
        :rtype: List[EcosystemRelationshipsChannelsData]
        """
        return self._data

    @data.setter
    def data(self, data: List[EcosystemRelationshipsChannelsData]):
        """Sets the data of this EcosystemRelationshipsChannels.


        :param data: The data of this EcosystemRelationshipsChannels.
        :type data: List[EcosystemRelationshipsChannelsData]
        """

        self._data = data
