# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.log import Log  # noqa: F401,E501
from swagger_server import util


class LogData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Log=None):  # noqa: E501
        """LogData - a model defined in Swagger

        :param data: The data of this LogData.  # noqa: E501
        :type data: Log
        """
        self.swagger_types = {
            'data': Log
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'LogData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LogData of this LogData.  # noqa: E501
        :rtype: LogData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Log:
        """Gets the data of this LogData.


        :return: The data of this LogData.
        :rtype: Log
        """
        return self._data

    @data.setter
    def data(self, data: Log):
        """Sets the data of this LogData.


        :param data: The data of this LogData.
        :type data: Log
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
