# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.package_attributes import PackageAttributes  # noqa: F401,E501
from swagger_server.models.package_relationships import PackageRelationships  # noqa: F401,E501
from swagger_server import util


class Package(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, type: str=None, attributes: PackageAttributes=None, relationships: PackageRelationships=None):  # noqa: E501
        """Package - a model defined in Swagger

        :param id: The id of this Package.  # noqa: E501
        :type id: str
        :param type: The type of this Package.  # noqa: E501
        :type type: str
        :param attributes: The attributes of this Package.  # noqa: E501
        :type attributes: PackageAttributes
        :param relationships: The relationships of this Package.  # noqa: E501
        :type relationships: PackageRelationships
        """
        self.swagger_types = {
            'id': str,
            'type': str,
            'attributes': PackageAttributes,
            'relationships': PackageRelationships
        }

        self.attribute_map = {
            'id': 'id',
            'type': 'type',
            'attributes': 'attributes',
            'relationships': 'relationships'
        }
        self._id = id
        self._type = type
        self._attributes = attributes
        self._relationships = relationships

    @classmethod
    def from_dict(cls, dikt) -> 'Package':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Package of this Package.  # noqa: E501
        :rtype: Package
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Package.


        :return: The id of this Package.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Package.


        :param id: The id of this Package.
        :type id: str
        """

        self._id = id

    @property
    def type(self) -> str:
        """Gets the type of this Package.


        :return: The type of this Package.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Package.


        :param type: The type of this Package.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def attributes(self) -> PackageAttributes:
        """Gets the attributes of this Package.


        :return: The attributes of this Package.
        :rtype: PackageAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: PackageAttributes):
        """Sets the attributes of this Package.


        :param attributes: The attributes of this Package.
        :type attributes: PackageAttributes
        """

        self._attributes = attributes

    @property
    def relationships(self) -> PackageRelationships:
        """Gets the relationships of this Package.


        :return: The relationships of this Package.
        :rtype: PackageRelationships
        """
        return self._relationships

    @relationships.setter
    def relationships(self, relationships: PackageRelationships):
        """Sets the relationships of this Package.


        :param relationships: The relationships of this Package.
        :type relationships: PackageRelationships
        """

        self._relationships = relationships
