# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.build_relationships_missingpackages import BuildRelationshipsMissingpackages  # noqa: F401,E501
from swagger_server.models.recipe_revision_relationships_recipe import RecipeRevisionRelationshipsRecipe  # noqa: F401,E501
from swagger_server import util


class RecipeRevisionRelationships(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, recipe: RecipeRevisionRelationshipsRecipe=None, packages: BuildRelationshipsMissingpackages=None):  # noqa: E501
        """RecipeRevisionRelationships - a model defined in Swagger

        :param recipe: The recipe of this RecipeRevisionRelationships.  # noqa: E501
        :type recipe: RecipeRevisionRelationshipsRecipe
        :param packages: The packages of this RecipeRevisionRelationships.  # noqa: E501
        :type packages: BuildRelationshipsMissingpackages
        """
        self.swagger_types = {
            'recipe': RecipeRevisionRelationshipsRecipe,
            'packages': BuildRelationshipsMissingpackages
        }

        self.attribute_map = {
            'recipe': 'recipe',
            'packages': 'packages'
        }
        self._recipe = recipe
        self._packages = packages

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeRevisionRelationships':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeRevision_relationships of this RecipeRevisionRelationships.  # noqa: E501
        :rtype: RecipeRevisionRelationships
        """
        return util.deserialize_model(dikt, cls)

    @property
    def recipe(self) -> RecipeRevisionRelationshipsRecipe:
        """Gets the recipe of this RecipeRevisionRelationships.


        :return: The recipe of this RecipeRevisionRelationships.
        :rtype: RecipeRevisionRelationshipsRecipe
        """
        return self._recipe

    @recipe.setter
    def recipe(self, recipe: RecipeRevisionRelationshipsRecipe):
        """Sets the recipe of this RecipeRevisionRelationships.


        :param recipe: The recipe of this RecipeRevisionRelationships.
        :type recipe: RecipeRevisionRelationshipsRecipe
        """

        self._recipe = recipe

    @property
    def packages(self) -> BuildRelationshipsMissingpackages:
        """Gets the packages of this RecipeRevisionRelationships.


        :return: The packages of this RecipeRevisionRelationships.
        :rtype: BuildRelationshipsMissingpackages
        """
        return self._packages

    @packages.setter
    def packages(self, packages: BuildRelationshipsMissingpackages):
        """Sets the packages of this RecipeRevisionRelationships.


        :param packages: The packages of this RecipeRevisionRelationships.
        :type packages: BuildRelationshipsMissingpackages
        """

        self._packages = packages
