# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.repo_relationships_commits import RepoRelationshipsCommits  # noqa: F401,E501
from swagger_server.models.repo_relationships_ecosystem import RepoRelationshipsEcosystem  # noqa: F401,E501
from swagger_server import util


class RepoRelationships(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ecosystem: RepoRelationshipsEcosystem=None, commits: RepoRelationshipsCommits=None):  # noqa: E501
        """RepoRelationships - a model defined in Swagger

        :param ecosystem: The ecosystem of this RepoRelationships.  # noqa: E501
        :type ecosystem: RepoRelationshipsEcosystem
        :param commits: The commits of this RepoRelationships.  # noqa: E501
        :type commits: RepoRelationshipsCommits
        """
        self.swagger_types = {
            'ecosystem': RepoRelationshipsEcosystem,
            'commits': RepoRelationshipsCommits
        }

        self.attribute_map = {
            'ecosystem': 'ecosystem',
            'commits': 'commits'
        }
        self._ecosystem = ecosystem
        self._commits = commits

    @classmethod
    def from_dict(cls, dikt) -> 'RepoRelationships':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Repo_relationships of this RepoRelationships.  # noqa: E501
        :rtype: RepoRelationships
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ecosystem(self) -> RepoRelationshipsEcosystem:
        """Gets the ecosystem of this RepoRelationships.


        :return: The ecosystem of this RepoRelationships.
        :rtype: RepoRelationshipsEcosystem
        """
        return self._ecosystem

    @ecosystem.setter
    def ecosystem(self, ecosystem: RepoRelationshipsEcosystem):
        """Sets the ecosystem of this RepoRelationships.


        :param ecosystem: The ecosystem of this RepoRelationships.
        :type ecosystem: RepoRelationshipsEcosystem
        """

        self._ecosystem = ecosystem

    @property
    def commits(self) -> RepoRelationshipsCommits:
        """Gets the commits of this RepoRelationships.


        :return: The commits of this RepoRelationships.
        :rtype: RepoRelationshipsCommits
        """
        return self._commits

    @commits.setter
    def commits(self, commits: RepoRelationshipsCommits):
        """Sets the commits of this RepoRelationships.


        :param commits: The commits of this RepoRelationships.
        :type commits: RepoRelationshipsCommits
        """

        self._commits = commits
