# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.repo_attributes import RepoAttributes  # noqa: F401,E501
from swagger_server.models.repo_relationships import RepoRelationships  # noqa: F401,E501
from swagger_server import util


class Repo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, type: str=None, attributes: RepoAttributes=None, relationships: RepoRelationships=None):  # noqa: E501
        """Repo - a model defined in Swagger

        :param id: The id of this Repo.  # noqa: E501
        :type id: str
        :param type: The type of this Repo.  # noqa: E501
        :type type: str
        :param attributes: The attributes of this Repo.  # noqa: E501
        :type attributes: RepoAttributes
        :param relationships: The relationships of this Repo.  # noqa: E501
        :type relationships: RepoRelationships
        """
        self.swagger_types = {
            'id': str,
            'type': str,
            'attributes': RepoAttributes,
            'relationships': RepoRelationships
        }

        self.attribute_map = {
            'id': 'id',
            'type': 'type',
            'attributes': 'attributes',
            'relationships': 'relationships'
        }
        self._id = id
        self._type = type
        self._attributes = attributes
        self._relationships = relationships

    @classmethod
    def from_dict(cls, dikt) -> 'Repo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Repo of this Repo.  # noqa: E501
        :rtype: Repo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Repo.


        :return: The id of this Repo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Repo.


        :param id: The id of this Repo.
        :type id: str
        """

        self._id = id

    @property
    def type(self) -> str:
        """Gets the type of this Repo.


        :return: The type of this Repo.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Repo.


        :param type: The type of this Repo.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def attributes(self) -> RepoAttributes:
        """Gets the attributes of this Repo.


        :return: The attributes of this Repo.
        :rtype: RepoAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: RepoAttributes):
        """Sets the attributes of this Repo.


        :param attributes: The attributes of this Repo.
        :type attributes: RepoAttributes
        """

        self._attributes = attributes

    @property
    def relationships(self) -> RepoRelationships:
        """Gets the relationships of this Repo.


        :return: The relationships of this Repo.
        :rtype: RepoRelationships
        """
        return self._relationships

    @relationships.setter
    def relationships(self, relationships: RepoRelationships):
        """Sets the relationships of this Repo.


        :param relationships: The relationships of this Repo.
        :type relationships: RepoRelationships
        """

        self._relationships = relationships
