# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.repo_relationships_commits_links import RepoRelationshipsCommitsLinks  # noqa: F401,E501
from swagger_server import util


class RepoRelationshipsCommits(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: RepoRelationshipsCommitsLinks=None):  # noqa: E501
        """RepoRelationshipsCommits - a model defined in Swagger

        :param links: The links of this RepoRelationshipsCommits.  # noqa: E501
        :type links: RepoRelationshipsCommitsLinks
        """
        self.swagger_types = {
            'links': RepoRelationshipsCommitsLinks
        }

        self.attribute_map = {
            'links': 'links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'RepoRelationshipsCommits':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Repo_relationships_commits of this RepoRelationshipsCommits.  # noqa: E501
        :rtype: RepoRelationshipsCommits
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> RepoRelationshipsCommitsLinks:
        """Gets the links of this RepoRelationshipsCommits.


        :return: The links of this RepoRelationshipsCommits.
        :rtype: RepoRelationshipsCommitsLinks
        """
        return self._links

    @links.setter
    def links(self, links: RepoRelationshipsCommitsLinks):
        """Sets the links of this RepoRelationshipsCommits.


        :param links: The links of this RepoRelationshipsCommits.
        :type links: RepoRelationshipsCommitsLinks
        """

        self._links = links
