# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class UserData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: User=None):  # noqa: E501
        """UserData - a model defined in Swagger

        :param data: The data of this UserData.  # noqa: E501
        :type data: User
        """
        self.swagger_types = {
            'data': User
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'UserData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserData of this UserData.  # noqa: E501
        :rtype: UserData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> User:
        """Gets the data of this UserData.


        :return: The data of this UserData.
        :rtype: User
        """
        return self._data

    @data.setter
    def data(self, data: User):
        """Sets the data of this UserData.


        :param data: The data of this UserData.
        :type data: User
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
