# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class UserList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[User]=None):  # noqa: E501
        """UserList - a model defined in Swagger

        :param data: The data of this UserList.  # noqa: E501
        :type data: List[User]
        """
        self.swagger_types = {
            'data': List[User]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'UserList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserList of this UserList.  # noqa: E501
        :rtype: UserList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[User]:
        """Gets the data of this UserList.


        :return: The data of this UserList.
        :rtype: List[User]
        """
        return self._data

    @data.setter
    def data(self, data: List[User]):
        """Sets the data of this UserList.


        :param data: The data of this UserList.
        :type data: List[User]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
