# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BuildAttributes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None):  # noqa: E501
        """BuildAttributes - a model defined in Swagger

        :param status: The status of this BuildAttributes.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'status': str
        }

        self.attribute_map = {
            'status': 'status'
        }
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'BuildAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Build_attributes of this BuildAttributes.  # noqa: E501
        :rtype: BuildAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this BuildAttributes.


        :return: The status of this BuildAttributes.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this BuildAttributes.


        :param status: The status of this BuildAttributes.
        :type status: str
        """
        allowed_values = ["active", "error", "new", "stopped", "stopping", "success"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
