# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.build_relationships_missingrecipes_data import BuildRelationshipsMissingrecipesData  # noqa: F401,E501
from swagger_server import util


class BuildRelationshipsMissingrecipes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[BuildRelationshipsMissingrecipesData]=None):  # noqa: E501
        """BuildRelationshipsMissingrecipes - a model defined in Swagger

        :param data: The data of this BuildRelationshipsMissingrecipes.  # noqa: E501
        :type data: List[BuildRelationshipsMissingrecipesData]
        """
        self.swagger_types = {
            'data': List[BuildRelationshipsMissingrecipesData]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'BuildRelationshipsMissingrecipes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Build_relationships_missingrecipes of this BuildRelationshipsMissingrecipes.  # noqa: E501
        :rtype: BuildRelationshipsMissingrecipes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[BuildRelationshipsMissingrecipesData]:
        """Gets the data of this BuildRelationshipsMissingrecipes.


        :return: The data of this BuildRelationshipsMissingrecipes.
        :rtype: List[BuildRelationshipsMissingrecipesData]
        """
        return self._data

    @data.setter
    def data(self, data: List[BuildRelationshipsMissingrecipesData]):
        """Sets the data of this BuildRelationshipsMissingrecipes.


        :param data: The data of this BuildRelationshipsMissingrecipes.
        :type data: List[BuildRelationshipsMissingrecipesData]
        """

        self._data = data
