# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Channel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, branch: str=None):  # noqa: E501
        """Channel - a model defined in Swagger

        :param id: The id of this Channel.  # noqa: E501
        :type id: int
        :param name: The name of this Channel.  # noqa: E501
        :type name: str
        :param branch: The branch of this Channel.  # noqa: E501
        :type branch: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'branch': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'branch': 'branch'
        }
        self._id = id
        self._name = name
        self._branch = branch

    @classmethod
    def from_dict(cls, dikt) -> 'Channel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Channel of this Channel.  # noqa: E501
        :rtype: Channel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Channel.


        :return: The id of this Channel.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Channel.


        :param id: The id of this Channel.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Channel.


        :return: The name of this Channel.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Channel.


        :param name: The name of this Channel.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def branch(self) -> str:
        """Gets the branch of this Channel.


        :return: The branch of this Channel.
        :rtype: str
        """
        return self._branch

    @branch.setter
    def branch(self, branch: str):
        """Sets the branch of this Channel.


        :param branch: The branch of this Channel.
        :type branch: str
        """
        if branch is None:
            raise ValueError("Invalid value for `branch`, must not be `None`")  # noqa: E501

        self._branch = branch
