# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CommitAttributes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sha: str=None):  # noqa: E501
        """CommitAttributes - a model defined in Swagger

        :param sha: The sha of this CommitAttributes.  # noqa: E501
        :type sha: str
        """
        self.swagger_types = {
            'sha': str
        }

        self.attribute_map = {
            'sha': 'sha'
        }
        self._sha = sha

    @classmethod
    def from_dict(cls, dikt) -> 'CommitAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Commit_attributes of this CommitAttributes.  # noqa: E501
        :rtype: CommitAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sha(self) -> str:
        """Gets the sha of this CommitAttributes.


        :return: The sha of this CommitAttributes.
        :rtype: str
        """
        return self._sha

    @sha.setter
    def sha(self, sha: str):
        """Sets the sha of this CommitAttributes.


        :param sha: The sha of this CommitAttributes.
        :type sha: str
        """

        self._sha = sha
