# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.repo import Repo  # noqa: F401,E501
from swagger_server import util


class Commit(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, sha: str=None, repo: Repo=None):  # noqa: E501
        """Commit - a model defined in Swagger

        :param id: The id of this Commit.  # noqa: E501
        :type id: int
        :param sha: The sha of this Commit.  # noqa: E501
        :type sha: str
        :param repo: The repo of this Commit.  # noqa: E501
        :type repo: Repo
        """
        self.swagger_types = {
            'id': int,
            'sha': str,
            'repo': Repo
        }

        self.attribute_map = {
            'id': 'id',
            'sha': 'sha',
            'repo': 'repo'
        }
        self._id = id
        self._sha = sha
        self._repo = repo

    @classmethod
    def from_dict(cls, dikt) -> 'Commit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Commit of this Commit.  # noqa: E501
        :rtype: Commit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Commit.


        :return: The id of this Commit.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Commit.


        :param id: The id of this Commit.
        :type id: int
        """

        self._id = id

    @property
    def sha(self) -> str:
        """Gets the sha of this Commit.


        :return: The sha of this Commit.
        :rtype: str
        """
        return self._sha

    @sha.setter
    def sha(self, sha: str):
        """Sets the sha of this Commit.


        :param sha: The sha of this Commit.
        :type sha: str
        """

        self._sha = sha

    @property
    def repo(self) -> Repo:
        """Gets the repo of this Commit.


        :return: The repo of this Commit.
        :rtype: Repo
        """
        return self._repo

    @repo.setter
    def repo(self, repo: Repo):
        """Sets the repo of this Commit.


        :param repo: The repo of this Commit.
        :type repo: Repo
        """

        self._repo = repo
