# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.commit_relationships_channel_data import CommitRelationshipsChannelData  # noqa: F401,E501
from swagger_server import util


class CommitRelationshipsChannel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: CommitRelationshipsChannelData=None):  # noqa: E501
        """CommitRelationshipsChannel - a model defined in Swagger

        :param data: The data of this CommitRelationshipsChannel.  # noqa: E501
        :type data: CommitRelationshipsChannelData
        """
        self.swagger_types = {
            'data': CommitRelationshipsChannelData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'CommitRelationshipsChannel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Commit_relationships_channel of this CommitRelationshipsChannel.  # noqa: E501
        :rtype: CommitRelationshipsChannel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> CommitRelationshipsChannelData:
        """Gets the data of this CommitRelationshipsChannel.


        :return: The data of this CommitRelationshipsChannel.
        :rtype: CommitRelationshipsChannelData
        """
        return self._data

    @data.setter
    def data(self, data: CommitRelationshipsChannelData):
        """Sets the data of this CommitRelationshipsChannel.


        :param data: The data of this CommitRelationshipsChannel.
        :type data: CommitRelationshipsChannelData
        """

        self._data = data
