# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.commit_relationships_repo_data import CommitRelationshipsRepoData  # noqa: F401,E501
from swagger_server import util


class CommitRelationshipsRepo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: CommitRelationshipsRepoData=None):  # noqa: E501
        """CommitRelationshipsRepo - a model defined in Swagger

        :param data: The data of this CommitRelationshipsRepo.  # noqa: E501
        :type data: CommitRelationshipsRepoData
        """
        self.swagger_types = {
            'data': CommitRelationshipsRepoData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'CommitRelationshipsRepo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Commit_relationships_repo of this CommitRelationshipsRepo.  # noqa: E501
        :rtype: CommitRelationshipsRepo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> CommitRelationshipsRepoData:
        """Gets the data of this CommitRelationshipsRepo.


        :return: The data of this CommitRelationshipsRepo.
        :rtype: CommitRelationshipsRepoData
        """
        return self._data

    @data.setter
    def data(self, data: CommitRelationshipsRepoData):
        """Sets the data of this CommitRelationshipsRepo.


        :param data: The data of this CommitRelationshipsRepo.
        :type data: CommitRelationshipsRepoData
        """

        self._data = data
