# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.commit_relationships_builds_data import CommitRelationshipsBuildsData  # noqa: F401,E501
from swagger_server import util


class CommitRelationshipsBuilds(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[CommitRelationshipsBuildsData]=None):  # noqa: E501
        """CommitRelationshipsBuilds - a model defined in Swagger

        :param data: The data of this CommitRelationshipsBuilds.  # noqa: E501
        :type data: List[CommitRelationshipsBuildsData]
        """
        self.swagger_types = {
            'data': List[CommitRelationshipsBuildsData]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'CommitRelationshipsBuilds':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Commit_relationships_builds of this CommitRelationshipsBuilds.  # noqa: E501
        :rtype: CommitRelationshipsBuilds
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[CommitRelationshipsBuildsData]:
        """Gets the data of this CommitRelationshipsBuilds.


        :return: The data of this CommitRelationshipsBuilds.
        :rtype: List[CommitRelationshipsBuildsData]
        """
        return self._data

    @data.setter
    def data(self, data: List[CommitRelationshipsBuildsData]):
        """Sets the data of this CommitRelationshipsBuilds.


        :param data: The data of this CommitRelationshipsBuilds.
        :type data: List[CommitRelationshipsBuildsData]
        """

        self._data = data
