# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.commit_relationships_channel import CommitRelationshipsChannel  # noqa: F401,E501
from swagger_server.models.commit_relationships_repo import CommitRelationshipsRepo  # noqa: F401,E501
from swagger_server import util


class CommitRelationships(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, repo: CommitRelationshipsRepo=None, channel: CommitRelationshipsChannel=None):  # noqa: E501
        """CommitRelationships - a model defined in Swagger

        :param repo: The repo of this CommitRelationships.  # noqa: E501
        :type repo: CommitRelationshipsRepo
        :param channel: The channel of this CommitRelationships.  # noqa: E501
        :type channel: CommitRelationshipsChannel
        """
        self.swagger_types = {
            'repo': CommitRelationshipsRepo,
            'channel': CommitRelationshipsChannel
        }

        self.attribute_map = {
            'repo': 'repo',
            'channel': 'channel'
        }
        self._repo = repo
        self._channel = channel

    @classmethod
    def from_dict(cls, dikt) -> 'CommitRelationships':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Commit_relationships of this CommitRelationships.  # noqa: E501
        :rtype: CommitRelationships
        """
        return util.deserialize_model(dikt, cls)

    @property
    def repo(self) -> CommitRelationshipsRepo:
        """Gets the repo of this CommitRelationships.


        :return: The repo of this CommitRelationships.
        :rtype: CommitRelationshipsRepo
        """
        return self._repo

    @repo.setter
    def repo(self, repo: CommitRelationshipsRepo):
        """Sets the repo of this CommitRelationships.


        :param repo: The repo of this CommitRelationships.
        :type repo: CommitRelationshipsRepo
        """

        self._repo = repo

    @property
    def channel(self) -> CommitRelationshipsChannel:
        """Gets the channel of this CommitRelationships.


        :return: The channel of this CommitRelationships.
        :rtype: CommitRelationshipsChannel
        """
        return self._channel

    @channel.setter
    def channel(self, channel: CommitRelationshipsChannel):
        """Sets the channel of this CommitRelationships.


        :param channel: The channel of this CommitRelationships.
        :type channel: CommitRelationshipsChannel
        """

        self._channel = channel
