# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Credentials(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_name: str=None, password: str=None):  # noqa: E501
        """Credentials - a model defined in Swagger

        :param user_name: The user_name of this Credentials.  # noqa: E501
        :type user_name: str
        :param password: The password of this Credentials.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'user_name': str,
            'password': str
        }

        self.attribute_map = {
            'user_name': 'user-name',
            'password': 'password'
        }
        self._user_name = user_name
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'Credentials':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Credentials of this Credentials.  # noqa: E501
        :rtype: Credentials
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_name(self) -> str:
        """Gets the user_name of this Credentials.


        :return: The user_name of this Credentials.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name: str):
        """Sets the user_name of this Credentials.


        :param user_name: The user_name of this Credentials.
        :type user_name: str
        """

        self._user_name = user_name

    @property
    def password(self) -> str:
        """Gets the password of this Credentials.


        :return: The password of this Credentials.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this Credentials.


        :param password: The password of this Credentials.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
