# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ecosystem_relationships_profiles_links import EcosystemRelationshipsProfilesLinks  # noqa: F401,E501
from swagger_server import util


class EcosystemRelationshipsProfiles(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: EcosystemRelationshipsProfilesLinks=None):  # noqa: E501
        """EcosystemRelationshipsProfiles - a model defined in Swagger

        :param links: The links of this EcosystemRelationshipsProfiles.  # noqa: E501
        :type links: EcosystemRelationshipsProfilesLinks
        """
        self.swagger_types = {
            'links': EcosystemRelationshipsProfilesLinks
        }

        self.attribute_map = {
            'links': 'links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'EcosystemRelationshipsProfiles':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ecosystem_relationships_profiles of this EcosystemRelationshipsProfiles.  # noqa: E501
        :rtype: EcosystemRelationshipsProfiles
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> EcosystemRelationshipsProfilesLinks:
        """Gets the links of this EcosystemRelationshipsProfiles.


        :return: The links of this EcosystemRelationshipsProfiles.
        :rtype: EcosystemRelationshipsProfilesLinks
        """
        return self._links

    @links.setter
    def links(self, links: EcosystemRelationshipsProfilesLinks):
        """Sets the links of this EcosystemRelationshipsProfiles.


        :param links: The links of this EcosystemRelationshipsProfiles.
        :type links: EcosystemRelationshipsProfilesLinks
        """

        self._links = links
