# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ecosystem import Ecosystem  # noqa: F401,E501
from swagger_server import util


class EcosystemData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Ecosystem=None):  # noqa: E501
        """EcosystemData - a model defined in Swagger

        :param data: The data of this EcosystemData.  # noqa: E501
        :type data: Ecosystem
        """
        self.swagger_types = {
            'data': Ecosystem
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'EcosystemData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EcosystemData of this EcosystemData.  # noqa: E501
        :rtype: EcosystemData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Ecosystem:
        """Gets the data of this EcosystemData.


        :return: The data of this EcosystemData.
        :rtype: Ecosystem
        """
        return self._data

    @data.setter
    def data(self, data: Ecosystem):
        """Sets the data of this EcosystemData.


        :param data: The data of this EcosystemData.
        :type data: Ecosystem
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
