# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ecosystem_relationships_channels_links import EcosystemRelationshipsChannelsLinks  # noqa: F401,E501
from swagger_server import util


class EcosystemRelationshipsChannels(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: EcosystemRelationshipsChannelsLinks=None):  # noqa: E501
        """EcosystemRelationshipsChannels - a model defined in Swagger

        :param links: The links of this EcosystemRelationshipsChannels.  # noqa: E501
        :type links: EcosystemRelationshipsChannelsLinks
        """
        self.swagger_types = {
            'links': EcosystemRelationshipsChannelsLinks
        }

        self.attribute_map = {
            'links': 'links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'EcosystemRelationshipsChannels':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ecosystem_relationships_channels of this EcosystemRelationshipsChannels.  # noqa: E501
        :rtype: EcosystemRelationshipsChannels
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> EcosystemRelationshipsChannelsLinks:
        """Gets the links of this EcosystemRelationshipsChannels.


        :return: The links of this EcosystemRelationshipsChannels.
        :rtype: EcosystemRelationshipsChannelsLinks
        """
        return self._links

    @links.setter
    def links(self, links: EcosystemRelationshipsChannelsLinks):
        """Sets the links of this EcosystemRelationshipsChannels.


        :param links: The links of this EcosystemRelationshipsChannels.
        :type links: EcosystemRelationshipsChannelsLinks
        """

        self._links = links
