# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ecosystem import Ecosystem  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[Ecosystem]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param data: The data of this InlineResponse200.  # noqa: E501
        :type data: List[Ecosystem]
        """
        self.swagger_types = {
            'data': List[Ecosystem]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Ecosystem]:
        """Gets the data of this InlineResponse200.


        :return: The data of this InlineResponse200.
        :rtype: List[Ecosystem]
        """
        return self._data

    @data.setter
    def data(self, data: List[Ecosystem]):
        """Sets the data of this InlineResponse200.


        :param data: The data of this InlineResponse200.
        :type data: List[Ecosystem]
        """

        self._data = data
