# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.profile import Profile  # noqa: F401,E501
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[Profile]=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param data: The data of this InlineResponse2003.  # noqa: E501
        :type data: List[Profile]
        """
        self.swagger_types = {
            'data': List[Profile]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Profile]:
        """Gets the data of this InlineResponse2003.


        :return: The data of this InlineResponse2003.
        :rtype: List[Profile]
        """
        return self._data

    @data.setter
    def data(self, data: List[Profile]):
        """Sets the data of this InlineResponse2003.


        :param data: The data of this InlineResponse2003.
        :type data: List[Profile]
        """

        self._data = data
