# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.build import Build  # noqa: F401,E501
from swagger_server import util


class InlineResponse2009(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[Build]=None):  # noqa: E501
        """InlineResponse2009 - a model defined in Swagger

        :param data: The data of this InlineResponse2009.  # noqa: E501
        :type data: List[Build]
        """
        self.swagger_types = {
            'data': List[Build]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2009':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_9 of this InlineResponse2009.  # noqa: E501
        :rtype: InlineResponse2009
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Build]:
        """Gets the data of this InlineResponse2009.


        :return: The data of this InlineResponse2009.
        :rtype: List[Build]
        """
        return self._data

    @data.setter
    def data(self, data: List[Build]):
        """Sets the data of this InlineResponse2009.


        :param data: The data of this InlineResponse2009.
        :type data: List[Build]
        """

        self._data = data
