# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.channel import Channel  # noqa: F401,E501
from swagger_server import util


class InlineResponse2007(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[Channel]=None):  # noqa: E501
        """InlineResponse2007 - a model defined in Swagger

        :param data: The data of this InlineResponse2007.  # noqa: E501
        :type data: List[Channel]
        """
        self.swagger_types = {
            'data': List[Channel]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2007':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_7 of this InlineResponse2007.  # noqa: E501
        :rtype: InlineResponse2007
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Channel]:
        """Gets the data of this InlineResponse2007.


        :return: The data of this InlineResponse2007.
        :rtype: List[Channel]
        """
        return self._data

    @data.setter
    def data(self, data: List[Channel]):
        """Sets the data of this InlineResponse2007.


        :param data: The data of this InlineResponse2007.
        :type data: List[Channel]
        """

        self._data = data
