# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.profile import Profile  # noqa: F401,E501
from swagger_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Profile=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param data: The data of this InlineResponse2004.  # noqa: E501
        :type data: Profile
        """
        self.swagger_types = {
            'data': Profile
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Profile:
        """Gets the data of this InlineResponse2004.


        :return: The data of this InlineResponse2004.
        :rtype: Profile
        """
        return self._data

    @data.setter
    def data(self, data: Profile):
        """Sets the data of this InlineResponse2004.


        :param data: The data of this InlineResponse2004.
        :type data: Profile
        """

        self._data = data
