# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.log_attributes import LogAttributes  # noqa: F401,E501
from swagger_server import util


class Log(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, type: str=None, attributes: LogAttributes=None):  # noqa: E501
        """Log - a model defined in Swagger

        :param id: The id of this Log.  # noqa: E501
        :type id: str
        :param type: The type of this Log.  # noqa: E501
        :type type: str
        :param attributes: The attributes of this Log.  # noqa: E501
        :type attributes: LogAttributes
        """
        self.swagger_types = {
            'id': str,
            'type': str,
            'attributes': LogAttributes
        }

        self.attribute_map = {
            'id': 'id',
            'type': 'type',
            'attributes': 'attributes'
        }
        self._id = id
        self._type = type
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'Log':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Log of this Log.  # noqa: E501
        :rtype: Log
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Log.


        :return: The id of this Log.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Log.


        :param id: The id of this Log.
        :type id: str
        """

        self._id = id

    @property
    def type(self) -> str:
        """Gets the type of this Log.


        :return: The type of this Log.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Log.


        :param type: The type of this Log.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def attributes(self) -> LogAttributes:
        """Gets the attributes of this Log.


        :return: The attributes of this Log.
        :rtype: LogAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: LogAttributes):
        """Sets the attributes of this Log.


        :param attributes: The attributes of this Log.
        :type attributes: LogAttributes
        """

        self._attributes = attributes
