# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LogAttributes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, logs: str=None):  # noqa: E501
        """LogAttributes - a model defined in Swagger

        :param logs: The logs of this LogAttributes.  # noqa: E501
        :type logs: str
        """
        self.swagger_types = {
            'logs': str
        }

        self.attribute_map = {
            'logs': 'logs'
        }
        self._logs = logs

    @classmethod
    def from_dict(cls, dikt) -> 'LogAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Log_attributes of this LogAttributes.  # noqa: E501
        :rtype: LogAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def logs(self) -> str:
        """Gets the logs of this LogAttributes.


        :return: The logs of this LogAttributes.
        :rtype: str
        """
        return self._logs

    @logs.setter
    def logs(self, logs: str):
        """Sets the logs of this LogAttributes.


        :param logs: The logs of this LogAttributes.
        :type logs: str
        """

        self._logs = logs
