# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PackageAttributes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, package_id: str=None):  # noqa: E501
        """PackageAttributes - a model defined in Swagger

        :param package_id: The package_id of this PackageAttributes.  # noqa: E501
        :type package_id: str
        """
        self.swagger_types = {
            'package_id': str
        }

        self.attribute_map = {
            'package_id': 'package-id'
        }
        self._package_id = package_id

    @classmethod
    def from_dict(cls, dikt) -> 'PackageAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Package_attributes of this PackageAttributes.  # noqa: E501
        :rtype: PackageAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def package_id(self) -> str:
        """Gets the package_id of this PackageAttributes.


        :return: The package_id of this PackageAttributes.
        :rtype: str
        """
        return self._package_id

    @package_id.setter
    def package_id(self, package_id: str):
        """Sets the package_id of this PackageAttributes.


        :param package_id: The package_id of this PackageAttributes.
        :type package_id: str
        """

        self._package_id = package_id
