# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.package_relationships_reciperevision_data import PackageRelationshipsReciperevisionData  # noqa: F401,E501
from swagger_server import util


class PackageRelationshipsReciperevision(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: PackageRelationshipsReciperevisionData=None):  # noqa: E501
        """PackageRelationshipsReciperevision - a model defined in Swagger

        :param data: The data of this PackageRelationshipsReciperevision.  # noqa: E501
        :type data: PackageRelationshipsReciperevisionData
        """
        self.swagger_types = {
            'data': PackageRelationshipsReciperevisionData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'PackageRelationshipsReciperevision':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Package_relationships_reciperevision of this PackageRelationshipsReciperevision.  # noqa: E501
        :rtype: PackageRelationshipsReciperevision
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> PackageRelationshipsReciperevisionData:
        """Gets the data of this PackageRelationshipsReciperevision.


        :return: The data of this PackageRelationshipsReciperevision.
        :rtype: PackageRelationshipsReciperevisionData
        """
        return self._data

    @data.setter
    def data(self, data: PackageRelationshipsReciperevisionData):
        """Sets the data of this PackageRelationshipsReciperevision.


        :param data: The data of this PackageRelationshipsReciperevision.
        :type data: PackageRelationshipsReciperevisionData
        """

        self._data = data
