# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.profile_attributes import ProfileAttributes  # noqa: F401,E501
from swagger_server.models.profile_relationships import ProfileRelationships  # noqa: F401,E501
from swagger_server import util


class Profile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, type: str=None, attributes: ProfileAttributes=None, relationships: ProfileRelationships=None):  # noqa: E501
        """Profile - a model defined in Swagger

        :param id: The id of this Profile.  # noqa: E501
        :type id: int
        :param type: The type of this Profile.  # noqa: E501
        :type type: str
        :param attributes: The attributes of this Profile.  # noqa: E501
        :type attributes: ProfileAttributes
        :param relationships: The relationships of this Profile.  # noqa: E501
        :type relationships: ProfileRelationships
        """
        self.swagger_types = {
            'id': int,
            'type': str,
            'attributes': ProfileAttributes,
            'relationships': ProfileRelationships
        }

        self.attribute_map = {
            'id': 'id',
            'type': 'type',
            'attributes': 'attributes',
            'relationships': 'relationships'
        }
        self._id = id
        self._type = type
        self._attributes = attributes
        self._relationships = relationships

    @classmethod
    def from_dict(cls, dikt) -> 'Profile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Profile of this Profile.  # noqa: E501
        :rtype: Profile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Profile.


        :return: The id of this Profile.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Profile.


        :param id: The id of this Profile.
        :type id: int
        """

        self._id = id

    @property
    def type(self) -> str:
        """Gets the type of this Profile.


        :return: The type of this Profile.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Profile.


        :param type: The type of this Profile.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def attributes(self) -> ProfileAttributes:
        """Gets the attributes of this Profile.


        :return: The attributes of this Profile.
        :rtype: ProfileAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: ProfileAttributes):
        """Sets the attributes of this Profile.


        :param attributes: The attributes of this Profile.
        :type attributes: ProfileAttributes
        """

        self._attributes = attributes

    @property
    def relationships(self) -> ProfileRelationships:
        """Gets the relationships of this Profile.


        :return: The relationships of this Profile.
        :rtype: ProfileRelationships
        """
        return self._relationships

    @relationships.setter
    def relationships(self, relationships: ProfileRelationships):
        """Sets the relationships of this Profile.


        :param relationships: The relationships of this Profile.
        :type relationships: ProfileRelationships
        """

        self._relationships = relationships
