# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProfileAttributesOptions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, key: str=None, value: str=None):  # noqa: E501
        """ProfileAttributesOptions - a model defined in Swagger

        :param key: The key of this ProfileAttributesOptions.  # noqa: E501
        :type key: str
        :param value: The value of this ProfileAttributesOptions.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'key': str,
            'value': str
        }

        self.attribute_map = {
            'key': 'key',
            'value': 'value'
        }
        self._key = key
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'ProfileAttributesOptions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Profile_attributes_options of this ProfileAttributesOptions.  # noqa: E501
        :rtype: ProfileAttributesOptions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this ProfileAttributesOptions.


        :return: The key of this ProfileAttributesOptions.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this ProfileAttributesOptions.


        :param key: The key of this ProfileAttributesOptions.
        :type key: str
        """
        if key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501

        self._key = key

    @property
    def value(self) -> str:
        """Gets the value of this ProfileAttributesOptions.


        :return: The value of this ProfileAttributesOptions.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this ProfileAttributesOptions.


        :param value: The value of this ProfileAttributesOptions.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
