# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.repo_relationships_ecosystem import RepoRelationshipsEcosystem  # noqa: F401,E501
from swagger_server import util


class ProfileRelationships(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ecosystem: RepoRelationshipsEcosystem=None):  # noqa: E501
        """ProfileRelationships - a model defined in Swagger

        :param ecosystem: The ecosystem of this ProfileRelationships.  # noqa: E501
        :type ecosystem: RepoRelationshipsEcosystem
        """
        self.swagger_types = {
            'ecosystem': RepoRelationshipsEcosystem
        }

        self.attribute_map = {
            'ecosystem': 'ecosystem'
        }
        self._ecosystem = ecosystem

    @classmethod
    def from_dict(cls, dikt) -> 'ProfileRelationships':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Profile_relationships of this ProfileRelationships.  # noqa: E501
        :rtype: ProfileRelationships
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ecosystem(self) -> RepoRelationshipsEcosystem:
        """Gets the ecosystem of this ProfileRelationships.


        :return: The ecosystem of this ProfileRelationships.
        :rtype: RepoRelationshipsEcosystem
        """
        return self._ecosystem

    @ecosystem.setter
    def ecosystem(self, ecosystem: RepoRelationshipsEcosystem):
        """Sets the ecosystem of this ProfileRelationships.


        :param ecosystem: The ecosystem of this ProfileRelationships.
        :type ecosystem: RepoRelationshipsEcosystem
        """

        self._ecosystem = ecosystem
