# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.recipe_revision import RecipeRevision  # noqa: F401,E501
from swagger_server import util


class RecipeRevisionList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[RecipeRevision]=None):  # noqa: E501
        """RecipeRevisionList - a model defined in Swagger

        :param data: The data of this RecipeRevisionList.  # noqa: E501
        :type data: List[RecipeRevision]
        """
        self.swagger_types = {
            'data': List[RecipeRevision]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeRevisionList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeRevisionList of this RecipeRevisionList.  # noqa: E501
        :rtype: RecipeRevisionList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[RecipeRevision]:
        """Gets the data of this RecipeRevisionList.


        :return: The data of this RecipeRevisionList.
        :rtype: List[RecipeRevision]
        """
        return self._data

    @data.setter
    def data(self, data: List[RecipeRevision]):
        """Sets the data of this RecipeRevisionList.


        :param data: The data of this RecipeRevisionList.
        :type data: List[RecipeRevision]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
