# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RecipeRevisionAttributes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, revision: str=None):  # noqa: E501
        """RecipeRevisionAttributes - a model defined in Swagger

        :param revision: The revision of this RecipeRevisionAttributes.  # noqa: E501
        :type revision: str
        """
        self.swagger_types = {
            'revision': str
        }

        self.attribute_map = {
            'revision': 'revision'
        }
        self._revision = revision

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeRevisionAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeRevision_attributes of this RecipeRevisionAttributes.  # noqa: E501
        :rtype: RecipeRevisionAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def revision(self) -> str:
        """Gets the revision of this RecipeRevisionAttributes.


        :return: The revision of this RecipeRevisionAttributes.
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision: str):
        """Sets the revision of this RecipeRevisionAttributes.


        :param revision: The revision of this RecipeRevisionAttributes.
        :type revision: str
        """

        self._revision = revision
