# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.recipe_revision_attributes import RecipeRevisionAttributes  # noqa: F401,E501
from swagger_server.models.recipe_revision_relationships import RecipeRevisionRelationships  # noqa: F401,E501
from swagger_server import util


class RecipeRevision(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, type: str=None, attributes: RecipeRevisionAttributes=None, relationships: RecipeRevisionRelationships=None):  # noqa: E501
        """RecipeRevision - a model defined in Swagger

        :param id: The id of this RecipeRevision.  # noqa: E501
        :type id: str
        :param type: The type of this RecipeRevision.  # noqa: E501
        :type type: str
        :param attributes: The attributes of this RecipeRevision.  # noqa: E501
        :type attributes: RecipeRevisionAttributes
        :param relationships: The relationships of this RecipeRevision.  # noqa: E501
        :type relationships: RecipeRevisionRelationships
        """
        self.swagger_types = {
            'id': str,
            'type': str,
            'attributes': RecipeRevisionAttributes,
            'relationships': RecipeRevisionRelationships
        }

        self.attribute_map = {
            'id': 'id',
            'type': 'type',
            'attributes': 'attributes',
            'relationships': 'relationships'
        }
        self._id = id
        self._type = type
        self._attributes = attributes
        self._relationships = relationships

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeRevision':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeRevision of this RecipeRevision.  # noqa: E501
        :rtype: RecipeRevision
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this RecipeRevision.


        :return: The id of this RecipeRevision.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this RecipeRevision.


        :param id: The id of this RecipeRevision.
        :type id: str
        """

        self._id = id

    @property
    def type(self) -> str:
        """Gets the type of this RecipeRevision.


        :return: The type of this RecipeRevision.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this RecipeRevision.


        :param type: The type of this RecipeRevision.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def attributes(self) -> RecipeRevisionAttributes:
        """Gets the attributes of this RecipeRevision.


        :return: The attributes of this RecipeRevision.
        :rtype: RecipeRevisionAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: RecipeRevisionAttributes):
        """Sets the attributes of this RecipeRevision.


        :param attributes: The attributes of this RecipeRevision.
        :type attributes: RecipeRevisionAttributes
        """

        self._attributes = attributes

    @property
    def relationships(self) -> RecipeRevisionRelationships:
        """Gets the relationships of this RecipeRevision.


        :return: The relationships of this RecipeRevision.
        :rtype: RecipeRevisionRelationships
        """
        return self._relationships

    @relationships.setter
    def relationships(self, relationships: RecipeRevisionRelationships):
        """Sets the relationships of this RecipeRevision.


        :param relationships: The relationships of this RecipeRevision.
        :type relationships: RecipeRevisionRelationships
        """

        self._relationships = relationships
