# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.recipe import Recipe  # noqa: F401,E501
from swagger_server import util


class RecipeData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Recipe=None):  # noqa: E501
        """RecipeData - a model defined in Swagger

        :param data: The data of this RecipeData.  # noqa: E501
        :type data: Recipe
        """
        self.swagger_types = {
            'data': Recipe
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeData of this RecipeData.  # noqa: E501
        :rtype: RecipeData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Recipe:
        """Gets the data of this RecipeData.


        :return: The data of this RecipeData.
        :rtype: Recipe
        """
        return self._data

    @data.setter
    def data(self, data: Recipe):
        """Sets the data of this RecipeData.


        :param data: The data of this RecipeData.
        :type data: Recipe
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
