# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.recipe_relationships_revisions_links import RecipeRelationshipsRevisionsLinks  # noqa: F401,E501
from swagger_server import util


class RecipeRelationshipsRevisions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: RecipeRelationshipsRevisionsLinks=None):  # noqa: E501
        """RecipeRelationshipsRevisions - a model defined in Swagger

        :param links: The links of this RecipeRelationshipsRevisions.  # noqa: E501
        :type links: RecipeRelationshipsRevisionsLinks
        """
        self.swagger_types = {
            'links': RecipeRelationshipsRevisionsLinks
        }

        self.attribute_map = {
            'links': 'links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeRelationshipsRevisions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Recipe_relationships_revisions of this RecipeRelationshipsRevisions.  # noqa: E501
        :rtype: RecipeRelationshipsRevisions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> RecipeRelationshipsRevisionsLinks:
        """Gets the links of this RecipeRelationshipsRevisions.


        :return: The links of this RecipeRelationshipsRevisions.
        :rtype: RecipeRelationshipsRevisionsLinks
        """
        return self._links

    @links.setter
    def links(self, links: RecipeRelationshipsRevisionsLinks):
        """Sets the links of this RecipeRelationshipsRevisions.


        :param links: The links of this RecipeRelationshipsRevisions.
        :type links: RecipeRelationshipsRevisionsLinks
        """

        self._links = links
