# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.recipe_revision import RecipeRevision  # noqa: F401,E501
from swagger_server import util


class RecipeRevisionData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: RecipeRevision=None):  # noqa: E501
        """RecipeRevisionData - a model defined in Swagger

        :param data: The data of this RecipeRevisionData.  # noqa: E501
        :type data: RecipeRevision
        """
        self.swagger_types = {
            'data': RecipeRevision
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeRevisionData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeRevisionData of this RecipeRevisionData.  # noqa: E501
        :rtype: RecipeRevisionData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> RecipeRevision:
        """Gets the data of this RecipeRevisionData.


        :return: The data of this RecipeRevisionData.
        :rtype: RecipeRevision
        """
        return self._data

    @data.setter
    def data(self, data: RecipeRevision):
        """Sets the data of this RecipeRevisionData.


        :param data: The data of this RecipeRevisionData.
        :type data: RecipeRevision
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
