# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.build_relationships_missingrecipes_data import BuildRelationshipsMissingrecipesData  # noqa: F401,E501
from swagger_server import util


class RecipeRevisionRelationshipsRecipe(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: BuildRelationshipsMissingrecipesData=None):  # noqa: E501
        """RecipeRevisionRelationshipsRecipe - a model defined in Swagger

        :param data: The data of this RecipeRevisionRelationshipsRecipe.  # noqa: E501
        :type data: BuildRelationshipsMissingrecipesData
        """
        self.swagger_types = {
            'data': BuildRelationshipsMissingrecipesData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeRevisionRelationshipsRecipe':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeRevision_relationships_recipe of this RecipeRevisionRelationshipsRecipe.  # noqa: E501
        :rtype: RecipeRevisionRelationshipsRecipe
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> BuildRelationshipsMissingrecipesData:
        """Gets the data of this RecipeRevisionRelationshipsRecipe.


        :return: The data of this RecipeRevisionRelationshipsRecipe.
        :rtype: BuildRelationshipsMissingrecipesData
        """
        return self._data

    @data.setter
    def data(self, data: BuildRelationshipsMissingrecipesData):
        """Sets the data of this RecipeRevisionRelationshipsRecipe.


        :param data: The data of this RecipeRevisionRelationshipsRecipe.
        :type data: BuildRelationshipsMissingrecipesData
        """

        self._data = data
