# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.repo import Repo  # noqa: F401,E501
from swagger_server import util


class RepoData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Repo=None):  # noqa: E501
        """RepoData - a model defined in Swagger

        :param data: The data of this RepoData.  # noqa: E501
        :type data: Repo
        """
        self.swagger_types = {
            'data': Repo
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'RepoData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RepoData of this RepoData.  # noqa: E501
        :rtype: RepoData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Repo:
        """Gets the data of this RepoData.


        :return: The data of this RepoData.
        :rtype: Repo
        """
        return self._data

    @data.setter
    def data(self, data: Repo):
        """Sets the data of this RepoData.


        :param data: The data of this RepoData.
        :type data: Repo
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
