# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.repo_relationships_ecosystem_data import RepoRelationshipsEcosystemData  # noqa: F401,E501
from swagger_server import util


class RepoRelationshipsEcosystem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: RepoRelationshipsEcosystemData=None):  # noqa: E501
        """RepoRelationshipsEcosystem - a model defined in Swagger

        :param data: The data of this RepoRelationshipsEcosystem.  # noqa: E501
        :type data: RepoRelationshipsEcosystemData
        """
        self.swagger_types = {
            'data': RepoRelationshipsEcosystemData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'RepoRelationshipsEcosystem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Repo_relationships_ecosystem of this RepoRelationshipsEcosystem.  # noqa: E501
        :rtype: RepoRelationshipsEcosystem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> RepoRelationshipsEcosystemData:
        """Gets the data of this RepoRelationshipsEcosystem.


        :return: The data of this RepoRelationshipsEcosystem.
        :rtype: RepoRelationshipsEcosystemData
        """
        return self._data

    @data.setter
    def data(self, data: RepoRelationshipsEcosystemData):
        """Sets the data of this RepoRelationshipsEcosystem.


        :param data: The data of this RepoRelationshipsEcosystem.
        :type data: RepoRelationshipsEcosystemData
        """

        self._data = data
