# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RepoAttributes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, path: str=None):  # noqa: E501
        """RepoAttributes - a model defined in Swagger

        :param url: The url of this RepoAttributes.  # noqa: E501
        :type url: str
        :param path: The path of this RepoAttributes.  # noqa: E501
        :type path: str
        """
        self.swagger_types = {
            'url': str,
            'path': str
        }

        self.attribute_map = {
            'url': 'url',
            'path': 'path'
        }
        self._url = url
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'RepoAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Repo_attributes of this RepoAttributes.  # noqa: E501
        :rtype: RepoAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this RepoAttributes.


        :return: The url of this RepoAttributes.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this RepoAttributes.


        :param url: The url of this RepoAttributes.
        :type url: str
        """

        self._url = url

    @property
    def path(self) -> str:
        """Gets the path of this RepoAttributes.


        :return: The path of this RepoAttributes.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this RepoAttributes.


        :param path: The path of this RepoAttributes.
        :type path: str
        """

        self._path = path
