# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Repo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, url: str=None, path: str=None):  # noqa: E501
        """Repo - a model defined in Swagger

        :param id: The id of this Repo.  # noqa: E501
        :type id: int
        :param url: The url of this Repo.  # noqa: E501
        :type url: str
        :param path: The path of this Repo.  # noqa: E501
        :type path: str
        """
        self.swagger_types = {
            'id': int,
            'url': str,
            'path': str
        }

        self.attribute_map = {
            'id': 'id',
            'url': 'url',
            'path': 'path'
        }
        self._id = id
        self._url = url
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'Repo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Repo of this Repo.  # noqa: E501
        :rtype: Repo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Repo.


        :return: The id of this Repo.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Repo.


        :param id: The id of this Repo.
        :type id: int
        """

        self._id = id

    @property
    def url(self) -> str:
        """Gets the url of this Repo.


        :return: The url of this Repo.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Repo.


        :param url: The url of this Repo.
        :type url: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def path(self) -> str:
        """Gets the path of this Repo.


        :return: The path of this Repo.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this Repo.


        :param path: The path of this Repo.
        :type path: str
        """

        self._path = path
